spring.application.name=sistema-manutencao
# Conexão com o banco
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_manutencao
spring.datasource.username=root
spring.datasource.password=TrePki92

# JPA cria/atualiza as tabelas automaticamente a partir das entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (padrão 8080)
server.port=8080

# JWT
jwt.secret=iY5sovmFWW2nbia18uA55H9RLisipjBW
jwt.expiration=86400000